Borsa.WebUI/Controllers/AdminRoleController.cs
using Borsa.WebUI.Identity;
using Borsa.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Borsa.WebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminRoleController : Controller
    {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<ApplicationUser> userManager;
        public AdminRoleController(RoleManager<IdentityRole> _roleManager, UserManager<ApplicationUser> _userManager)
        {
            roleManager = _roleManager;
            userManager = _userManager;
        }
        public IActionResult Index()
        {
            return View(roleManager.Roles);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (ModelState.IsValid)
            {
                var result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var x in result.Errors)
                    {
                        ModelState.AddModelError("", x.Description);
                    }
                }
            }
            return View(name);
        }


        public async Task<IActionResult> Delete(IdentityRole model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);
            await roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);

            var members = new List<ApplicationUser>();
            var nonmembers = new List<ApplicationUser>();

            foreach (var user in userManager.Users)
            {
                var list = await userManager.IsInRoleAsync(user, role.Name) ? members : nonmembers;
                list.Add(user);
            }

            var model = new RoleDetails()
            {
                Role = role,
                Members = members,
                NonMembers = nonmembers
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(RoleEditModel model)
        {
            IdentityResult result;

            if (ModelState.IsValid)
            {
                foreach (var userId in model.IdsToAdd ?? new string[] { })
                {
                    var user = await userManager.FindByIdAsync(userId);

                    if (user != null)
                    {
                        result = await userManager.AddToRoleAsync(user, model.RoleName);

                        if (!result.Succeeded)
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }

                }

                foreach (var userId in model.IdsToDelete ?? new string[] { })
                {
                    var user = await userManager.FindByIdAsync(userId);

                    if (user != null)
                    {
                        result = await userManager.RemoveFromRoleAsync(user, model.RoleName);

                        if (!result.Succeeded)
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                }
            }
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Edit", model.RoleId);
            }
        }
    }
}

Borsa.WebUI/Views/AdminRole/Create.cshtml
@model string
@{
    ViewData["Title"] = "Create Role";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<form asp-action="Create" method="post" class="col-md-9 mt-3 ml-3">
    <h2 class="">Add a new role</h2>

    <div class="text-danger" asp-validation-summary="All">  </div>

    <div class="form-group">
        <label for="name">Role Name</label>
        <input name="name" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary" value="Create" style="width:100px">Create</button>
    <a asp-action="Index" asp-controller="AdminRole" class="btn btn-warning" style="width:100px" value="Cancel">Cancel</a>
</form>

Borsa.WebUI/Views/AdminRole/Edit.cshtml
@model RoleDetails
@{
    ViewData["Title"] = "Edit Roles";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="text-danger" asp-validation-summary="ModelOnly"></div>


<form asp-action="Edit" method="post" class="col-md-12 mt-3 ml-2" >
    <h2 class="mb-4">Update Role</h2>
    <input type="hidden" name="RoleId" value="@Model.Role.Id" />
    <input type="hidden" name="RoleName" value="@Model.Role.Name" />

        <h4>
            Add to @Model.Role.Name
        </h4>
        <table class="table table-bordered table-striped table-sm">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr><td colspan="2">All User Are Members</td></tr>
            }
            else
            {
                @foreach (var user in Model.NonMembers)
                {
                    <tr>
                        <td width="750px">@user.UserName</td>
                        <td><input type="checkbox" name="IdsToAdd" value="@user.Id" /></td>
                    </tr>
                }
            }
        </table>
        
        
        <h4>
            Delete from @Model.Role.Name
        </h4>
        <table class="table table-bordered table-striped table-sm">
            @if (Model.Members.Count() == 0)
            {
                <tr><td colspan="2">No User Are Members</td></tr>
            }
            else
            {
                @foreach (var user in Model.Members)
                {
                    <tr>
                        <td width="750px">@user.UserName</td>
                        <td><input type="checkbox" name="IdsToDelete" value="@user.Id" /></td>
                    </tr>
                }
            }
        </table>

    <button type="submit" class="btn btn-primary" style="width:100px">Save</button>
    <a asp-action="Index" class="btn btn-warning" style="width:100px">Cancel</a>
</form>

Borsa.WebUI/Views/AdminRole/Index.cshtml
@model IEnumerable<IdentityRole>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-md-12 mb-4 mt-3 ml-1">
    <h2 class="mb-4 ml-1">
        Roles
        <a asp-action="Create" class="btn btn-primary ml-1" style="position:absolute;right:18px;width:120px">Add Role <i style="margin-left:5px" class="fas fa-plus"></i></a>
    </h2>

    <div class="text-danger" asp-validation-summary="ModelOnly"></div>

    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">
            @TempData["message"]
        </div>
    }

    <table id="tbl3" class="table table-striped table-bordered mt-3">
        <thead>
            <tr>
                <th>Delete</th>
                <th>Role Name</th>
                <th>Users</th>
            </tr>
        </thead>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" class="text-center">No Role</td>
            </tr>
        }
        else
        {
            <tbody>
                @foreach (var role in Model)
                {
                    <tr>
                        <td>
                            <a asp-controller="AdminRole" asp-action="Delete" asp-route-id="@role.Id" class="text-danger" data-toggle="tooltip" data-placement="top" onclick="return confirm('Are you sure you want to delete it?')"><strong>X</strong></a>
                        </td>
                        <td><a asp-action="Edit" asp-route-id="@role.Id">@role.Name</a></td>
                        <td identity-role="@role.Id"></td>
                    </tr>
                }
            </tbody>
        }
    </table>
</div>

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl3').dataTable({});
</script>