Borsa.WebUI/Controllers/CartController.cs
using Borsa.Business.Abstract;
using Borsa.Entities;
using Borsa.WebUI.Identity;
using Borsa.WebUI.Models;
using IyzipayCore;
using IyzipayCore.Model;
using IyzipayCore.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Borsa.WebUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private IOrderService _orderService;
        private UserManager<ApplicationUser> _userManager;
        private ICustomerAddressService _customerAddressService;
        private ICustomerCardService _customerCardService;
        public CartController(ICartService cartService, IOrderService orderService, UserManager<ApplicationUser> userManager, ICustomerAddressService customerAddressService, ICustomerCardService customerCardService)
        {
            _cartService = cartService;
            _userManager = userManager;
            _orderService = orderService;
            _customerAddressService = customerAddressService;
            _customerCardService = customerCardService;
        }
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            return View(new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (decimal)i.Product.Price,
                    DiscountedPrice = (decimal)i.Product.DiscountedPrice,
                    ImageUrl = i.Product.ImageUrl,
                    Qunatity = i.Quantity
                }).ToList()
            });
        }
        public IActionResult Wishlist()
        {
            var cart = _cartService.GetCartByUserWishlistId(_userManager.GetUserId(User));
            return View(new CartModel()
            {
                CartId = cart.Id,
                WishlistModels = cart.Wishlists.Select(i => new WishlistModel()
                {
                    WishlistId = i.Id,
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (decimal)i.Product.Price,
                    DiscountedPrice = (decimal)i.Product.DiscountedPrice,
                    ImageUrl = i.Product.ImageUrl,
                }).ToList()
            });
        }
        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult AddToWishlist(int productId)
        {
            _cartService.AddToWishlist(_userManager.GetUserId(User), productId);
            return RedirectToAction("Wishlist");
        }
        [HttpPost]
        public IActionResult DeleteFromWishlist(int productId)
        {
            _cartService.DeleteFromWishlist(_userManager.GetUserId(User), productId);
            return RedirectToAction("Wishlist");
        }
        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            _cartService.DeleteFromCart(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            var orderModel = new OrderModel();
            orderModel.CartModel = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (decimal)i.Product.Price,
                    DiscountedPrice = (decimal)i.Product.DiscountedPrice,
                    ImageUrl = i.Product.ImageUrl,
                    Qunatity = i.Quantity,
                }).ToList()
            };
            return View(orderModel);
        }
        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserId(userId);
                model.CartModel = new CartModel()
                {                   
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.Id,
                        ProductId = i.Product.Id,
                        Name = i.Product.Name,
                        Price = (decimal)i.Product.Price,
                        DiscountedPrice = (decimal)i.Product.DiscountedPrice,
                        ImageUrl = i.Product.ImageUrl,
                        Qunatity = i.Quantity
                    }).ToList()
                };
                // ÖDEME
                var payment = PaymentProcess(model);
                if (payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(cart.Id.ToString());
                    return View("Success");
                }
            }
            return View(model);
        }

        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            var order = new Order();
            order.OrderNumber = new Random().Next(111111, 999999).ToString();
            order.OrderState = "Pending";
            order.PaymentTypes = EnumPaymentTypes.CreditCart;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = DateTime.Now;
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.Email = model.Email;
            order.Phone = model.Phone;
            order.Address = model.Address;
            order.City = model.City;
            order.CardName = model.CardName;
            order.CardNumber = model.CardNumber;
            order.ExpirationMonth = model.ExpirationMonth;
            order.ExpirationYear = model.ExpirationYear;
            order.Cvv = model.Cvv;
            order.UserId = userId;
            order.Status = true;

            foreach (var x in model.CartModel.CartItems)
            {
                var orderitem = new OrderItem()
                {
                    Price = x.Price,
                    DiscountedPrice = x.DiscountedPrice,
                    Quantity = x.Qunatity,
                    ProductId = x.ProductId
                };
                order.OrderItems.Add(orderitem);
            }
            _orderService.Create(order);
        }

        private void ClearCart(string cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-Z5xplx8ztsKjPmzNS6y7WH86uBBGkshY";
            options.SecretKey = "sandbox-o1XGSGDjaNnorfWnqrYhaSeORBWfti1Z";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = Guid.NewGuid().ToString();
            request.Price = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.PaidPrice = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.CartModel.CartId.ToString();
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvv;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;


            //paymentCard.CardHolderName = "John Doe";
            //paymentCard.CardNumber = "5528790000000008";
            //paymentCard.ExpireMonth = "12";
            //paymentCard.ExpireYear = "2030";
            //paymentCard.Cvc = "123";

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = "John";
            buyer.Surname = "Doe";
            buyer.GsmNumber = "+905350000000";
            buyer.Email = "email@email.com";
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = "Istanbul";
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

Borsa.WebUI/Controllers/HomePageController.cs
using Borsa.Business.Abstract;
using Borsa.Entities;
using Borsa.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Borsa.WebUI.Controllers
{
    public class HomePageController : Controller
    {
        private IProductService _productService;

        public HomePageController(IProductService productService)
        {
            _productService = productService;

        }
        public IActionResult Index()
        {
            return View(new ProductListModel
            {
                Products = _productService.GetAll()
            });
        }
        public PartialViewResult Slider()
        {
            return PartialView();
        }
        public PartialViewResult HomeCategory()
        {
            return PartialView();
        }
        public IActionResult ProductList(string category, int page = 1)
        {         
            const int pageSize = 9;
            return View(new ProductListModel
            {               
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },
                Products = _productService.GetProductsByCategory(category, page, pageSize),
            });
           
        }
        public PartialViewResult PartialProductList()
        {
            return PartialView();
        }
        public IActionResult ProductDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails((int)id);
            if (product == null)
            {
                return NotFound();
            }
            return View(new ProductDetailsModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(x => x.Category).ToList()
            });
        }
        public IActionResult AboutUs()
        {
            return View();
        }
        public IActionResult SearchProduct(string q)
        {
            var word = HttpContext.Request.Query["q"].ToString();
            return View(new ProductListModel
            {
                Products = _productService.GetAll().Where(x=>x.Name.ToLower().Contains(word.ToLower()) == word.ToLower().Contains(word.ToLower())).ToList()
            });
        }
    }
}

Borsa.WebUI/Views/HomePage/AboutUs.cshtml
@{
    ViewData["Title"] = "AboutUs";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body>
    <div class="about">
        <div class="container">
            <h3 class="w3_agile_header">About Us</h3>
            <div class="about-agileinfo w3layouts">
                <div class="col-md-12 about-wthree-grids grid-top">
                    <h4>Borsa Market</h4>
                    <p class="top">Borsa Market has been serving its customers in Yozgat Center since 2007. Borsa Market is one of Yozgat's most established markets.</p>
                    <p>
                        Borsa Market is customer focused,
                        It shows its difference in Yozgat with its reliable, technological, innovative and affordable prices. In 2021, it aims to offer all the products you can find in a market to its customers in a fast and safe way with the virtual market application. The purpose of our virtual market is to save time and provide convenience to our customers. The products you order from Borsa Market will be at your door during the day.
                    </p>
                    <p><strong>Address:</strong> Emniyet Caddesi Müze Karşısı Yozgat/Merkez</p>
                    <p><strong>Telephone:</strong> (+90) 539 899 55 45</p>
                    <p><strong>E-Mail:</strong> erkilicbedirhan@hotmail.com</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Borsa.WebUI/Views/HomePage/Index.cshtml
@model ProductListModel
@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body>

    @* Slider *@
    <partial name="_Slider" />

    @* Offers *@
    @await Component.InvokeAsync("HomeMonth")

    @* Gallery *@
    @await Component.InvokeAsync("HomeGallery")

    @* Category *@
    <partial name="_HomeCategory" />

    @* Offers *@
    @await Component.InvokeAsync("HomeOffer")

</body>
</html>

Borsa.WebUI/Views/HomePage/ProductDetails.cshtml
@model ProductDetailsModel
@{
    ViewData["Title"] = "ProductDetails";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body>
    <div class="products">
        <div class="container">
            <div class="agileinfo_single">
                <div class="col-md-4 agileinfo_single_left">
                    <form asp-controller="Cart" asp-action="AddToWishlist" method="post" style="display:inline">
                        <input type="hidden" name="productId" value="@Model.Product.Id" />
                        <button type="submit"><i class="fas fa-heart" style="color:red"></i></button>
                    </form>
                    <img id="example" src="~/img/@Model.Product.ImageUrl" alt=" " class="img-responsive">
                </div>
                <div class="col-md-8 agileinfo_single_right">
                    <h2>@Model.Product.Name</h2>
                    <h4>Brand: @Model.Product.Brand</h4>
                    <div class="w3agile_description">
                        <h4>Description :</h4>
                        <p>
                            @Html.Raw(Model.Product.Description)
                        </p>
                    </div>
                    <div class="snipcart-item block">
                        @if (Model.Product.DiscountedPrice == Model.Product.Price)
                        {
                            <div class="snipcart-thumb agileinfo_single_right_snipcart">
                                <h3 class="m-sing">@Model.Product.Price ₺</h3>
                            </div>
                        }
                        else
                        {
                            <div class="snipcart-thumb agileinfo_single_right_snipcart">
                                <h3 class="m-sing">@Model.Product.DiscountedPrice ₺<s style="color:grey;margin-left:15px">@Model.Product.Price ₺</s></h3>
                            </div>
                        }
                        <form asp-controller="Cart" asp-action="AddToCart" method="post" class="form-inline">
                            <input type="hidden" name="productId" value="@Model.Product.Id" />
                            <div class="input-group mb-3">
                                <input type="number" name="quantity" class="form-control" value="1" min="1" step="1" style="width:100px" />
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-cart-plus"></i> Add To Cart
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
</body>
</html>

Borsa.WebUI/Views/HomePage/ProductList.cshtml
@model ProductListModel
@{
    ViewData["Title"] = "ProductList";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body>
    <div class="products">
        <div class="container">
            <div class="col-md-4 products-left" style="margin-top:40px">
                <div class="categories">
                    <h2>Categories</h2>
                    <ul class="cate">
                        @await Component.InvokeAsync("CategoryList")
                    </ul>
                </div>
            </div>
            <div class="col-md-8 products-right">
                <div class="agile_top_brands_grids">
                    <div class="row mb-5">
                        @foreach (var product in Model.Products)
                        {
                            <partial name="_PartialProductList" for="@product" />
                        }
                    </div>
                    <div page-model="@Model.PageInfo" style="text-align:center">

                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</body>
</html>

Borsa.WebUI/Views/HomePage/SearchProduct.cshtml
@model ProductListModel
@{
    ViewData["Title"] = "SearchProduct";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}


<!DOCTYPE html>
<html>
<body>
    <div class="products">
        <div class="container">
            <div class="col-md-4 products-left" style="margin-top:40px">
                <div class="categories">
                    <h2>Categories</h2>
                    <ul class="cate">
                        @await Component.InvokeAsync("CategoryList")
                    </ul>
                </div>
            </div>
            <div class="col-md-8 products-right">
                <div class="agile_top_brands_grids">
                    <div class="row mb-5">
                        @foreach (var product in Model.Products)
                        {
                            <partial name="_PartialProductList" for="@product" />
                        }
                    </div>                   
                    <div class="clearfix"> </div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</body>
</html>

Borsa.WebUI/Views/HomePage/_HomeCategory.cshtml
<div class="brands">
    <div class="container">
        <h3>Categories</h3>
        <div class="brands-agile">
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="/products/fruit,%20vegetables">Fruit, Vegetables</a></p>
                </div>
            </div>
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="/products/meat,%20chicken,%20fish">Meat, Chicken, Fish</a></p>
                </div>
            </div>
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="/products/milk,%20breakfast">Milk, Breakfast</a></p>
                </div>
            </div>

            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="/products/food,%20confectionery">Food, Confectionery</a></p>
                </div>
            </div>
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="/products/paper,%20cosmetics">Paper, Cosmetics</a></p>
                </div>
            </div>
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="/products/detergent,%20cleaning">Detergent, Cleaning</a></p>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

Borsa.WebUI/Views/HomePage/_PartialProductList.cshtml
@model Product

@if (User.Identity.IsAuthenticated)
{
    <div class="col-md-4 top_brand_left" style="margin-bottom:25px">
        <div class="hover14 column">
            @if (Model.DiscountedPrice == Model.Price)
            {
                <div class="agile_top_brand_left_grid">
                    <form asp-controller="Cart" asp-action="AddToWishlist" method="post" style="display:inline">
                        <input type="hidden" name="productId" value="@Model.Id" />
                        <button type="submit"><i class="fas fa-heart" style="color:red"></i></button>
                    </form>
                    <div class="agile_top_brand_left_grid1">
                        <figure>
                            <div class="snipcart-item block">
                                <div class="snipcart-thumb">
                                    <a href="/HomePage/ProductDetails/@Model.Id"><img title="" style="width:70%" alt="" src="~/img/@Model.ImageUrl"></a>
                                    <a href="/HomePage/ProductDetails/@Model.Id"><p>@Model.Name</p></a>
                                    <h4>@Model.Price ₺ </h4>
                                </div>
                                <br />
                                <a asp-controller="HomePage" asp-action="ProductDetails" asp-route-id="@Model.Id" style="margin-left:15px" class="btn btn-warning btn-sm">Details</a>
                                <form asp-controller="Cart" asp-action="AddToCart" method="post" style="display:inline">
                                    <input type="hidden" name="productId" value="@Model.Id" />
                                    <input type="hidden" name="quantity" value="1" />
                                    <button type="submit" class="btn btn-primary btn-sm">Add To Cart</button>
                                </form>
                            </div>
                        </figure>
                    </div>
                </div>
            }
            else
            {
                <div class="agile_top_brand_left_grid">
                    <form asp-controller="Cart" asp-action="AddToWishlist" method="post" style="display:inline">
                        <input type="hidden" name="productId" value="@Model.Id" />
                        <button type="submit"><i class="fas fa-heart" style="color:red"></i></button>
                    </form>
                    <div class="agile_top_brand_left_grid_pos">
                        <img src="~/home/images/offer.png" alt="" class="img-responsive" />
                    </div>
                    <div class="agile_top_brand_left_grid1">
                        <figure>
                            <div class="snipcart-item block">
                                <div class="snipcart-thumb">
                                    <a href="/HomePage/ProductDetails/@Model.Id"><img title="" style="width:70%" alt="" src="~/img/@Model.ImageUrl"></a>
                                    <a href="/HomePage/ProductDetails/@Model.Id"><p>@Model.Name</p></a>
                                    <h4>@Model.DiscountedPrice  ₺ <span>@Model.Price ₺</span></h4>
                                </div>
                                <br />
                                <a asp-controller="HomePage" asp-action="ProductDetails" asp-route-id="@Model.Id" style="margin-left:15px" class="btn btn-warning btn-sm">Details</a>
                                <form asp-controller="Cart" asp-action="AddToCart" method="post" style="display:inline">
                                    <input type="hidden" name="productId" value="@Model.Id" />
                                    <input type="hidden" name="quantity" value="1" />
                                    <button type="submit" class="btn btn-primary btn-sm">Add To Cart</button>
                                </form>
                            </div>
                        </figure>
                    </div>
                </div>
            }
        </div>
    </div>
}
else
{
    <div class="col-md-4 top_brand_left" style="margin-bottom:25px">
        <div class="hover14 column">
            @if (Model.DiscountedPrice == Model.Price)
            {
                <div class="agile_top_brand_left_grid">
                    <div class="agile_top_brand_left_grid1">
                        <figure>
                            <div class="snipcart-item block">
                                <div class="snipcart-thumb">
                                    <a href="/HomePage/ProductDetails/@Model.Id"><img title="" style="width:70%" alt="" src="~/img/@Model.ImageUrl"></a>
                                    <a href="/HomePage/ProductDetails/@Model.Id"><p>@Model.Name</p></a>
                                    <h4>@Model.Price ₺ </h4>
                                </div>
                                <div class="snipcart-details top_brand_home_details">
                                    <a asp-controller="HomePage" asp-action="ProductDetails" asp-route-id="@Model.Id" class="btn btn-warning btn-sm">Details</a>
                                </div>
                            </div>
                        </figure>
                    </div>
                </div>
            }
            else
            {
                <div class="agile_top_brand_left_grid">
                    <div class="agile_top_brand_left_grid_pos">
                        <img src="~/home/images/offer.png" alt="" class="img-responsive" />
                    </div>
                    <div class="agile_top_brand_left_grid1">
                        <figure>
                            <div class="snipcart-item block">
                                <div class="snipcart-thumb">
                                    <a href="/HomePage/ProductDetails/@Model.Id"><img title="" style="width:70%" alt="" src="~/img/@Model.ImageUrl"></a>
                                    <a href="/HomePage/ProductDetails/@Model.Id"><p>@Model.Name</p></a>
                                    <h4>@Model.DiscountedPrice  ₺ <span>@Model.Price ₺</span></h4>
                                </div>
                                <div class="snipcart-details top_brand_home_details">
                                    <a asp-controller="HomePage" asp-action="ProductDetails" asp-route-id="@Model.Id" class="btn btn-warning btn-sm">Details</a>
                                </div>
                            </div>
                        </figure>
                    </div>
                </div>
            }
        </div>
    </div>
}

Borsa.WebUI/Views/HomePage/_Slider.cshtml
<ul id="demo1">
    <li>
        <img src="~/home/images/11.jpg" alt="" />
        <div class="slide-desc">
            <h3>Access products easily with Borsa Market virtual market</h3>
        </div>
    </li>
    <li>
        <img src="~/home/images/22.jpg" alt="" />
        <div class="slide-desc">
            <h3>Find products at the best prices with Borsa Market</h3>
        </div>
    </li>
    <li>
        <img src="~/home/images/44.jpg" alt="" />
        <div class="slide-desc">
            <h3>You can follow the discounts by following us.</h3>
        </div>
    </li>
</ul>