Borsa.WebUI/Controllers/GraphicController.cs
using Borsa.DataAccess.Concrete.EfCore;
using Borsa.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Borsa.WebUI.Controllers
{
    public class GraphicController : Controller
    {
        public IActionResult PieChart()
        {
            return View();
        }
        public IActionResult VisualizeProductResult()
        {
            return Json(ProdList());
        }
        public List<PieChartModel> ProdList()
        {
            List<PieChartModel> cls = new List<PieChartModel>();
            using (var c = new BorsaContext())
            {
                cls = c.Products.Select(x => new PieChartModel
                {
                    product = x.Name,
                    stock = x.Stock
                }).ToList();
            }
            return cls;
        }

        public IActionResult LineChart()
        {
            return View();
        }
        public IActionResult VisualizeProductResult2()
        {
            return Json(ProdList2());
        }
        public List<LineChartModel> ProdList2()
        {
            List<LineChartModel> cls = new List<LineChartModel>();
            using (var c = new BorsaContext())
            {
                cls = c.Products.Select(x => new LineChartModel
                {
                    brand = x.Brand,
                    stock = x.Stock
                    
                }).ToList();
            }
            return cls;
        }

        public IActionResult ColumnChart()
        {
            return View();
        }
        public IActionResult VisualizeProductResult3()
        {
            return Json(ProdList3());
        }
        public List<ColumnChartModel> ProdList3()
        {
            List<ColumnChartModel> cls = new List<ColumnChartModel>();
            using (var c = new BorsaContext())
            {
                cls = c.Products.Select(x => new ColumnChartModel
                {
                    product = x.Name,
                    stock = x.Stock
                }).ToList();
            }
            return cls;
        }

    }
}

Borsa.WebUI/Views/Graphic/ColumnChart.cshtml
@{
    ViewData["Title"] = "ColumnChart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*<h2 style="margin-left:300px">Product - Stock Graphic</h2>*@
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult3", "Graphic")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stocks');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.product, obj.stock]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Product - Stock Graphic",
                width: 1020,
                height: 765,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('columnchart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnchart_div"></div>
</body>
</html>

Borsa.WebUI/Views/Graphic/LineChart.cshtml
@{
    ViewData["Title"] = "LineChart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@*<h2 style="margin-left:300px">Brand - Stock Graphic</h2>*@
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult2", "Graphic")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stock');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.brand,obj.stock]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Brand - Stock Graphic",
                width: 1020,
                height: 765,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.LineChart(document
                .getElementById('linechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="linechart_div"></div>
</body>
</html>

Borsa.WebUI/Views/Graphic/PieChart.cshtml
@{
    ViewData["Title"] = "PieChart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*<h2 style="margin-left:300px">Product - Stock Graphic</h2>*@
<!DOCTYPE html>
<html lang="en">
<head>   
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Graphic")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stock');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.product, obj.stock]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Product - Stock Graphic",
                width: 1020,
                height: 765,
                bar: { groupWidth: "100%" },
            };
            var columnChart = new google.visualization.PieChart(document
                .getElementById('piechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="piechart_div"></div>
</body>
</html>